# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    #TODO: Enable it after auth setup
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo_db_dir:/data/db
      - ./mongod.conf:/etc/mongod.conf
      - ./ssl/mongodb.pem:/etc/ssl/mongodb.pem
    command:
        - '-f'
        - '/etc/mongod.conf'
    ports:
      - 27017:27017
    logging:
        driver: "json-file"
        options:
            max-size: "2m"
            max-file: "2"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    logging:
        driver: "json-file"
        options:
            max-size: "2m"
            max-file: "2"
